"""Run SPRINT on T3, producing the raw scores the unified evaluation layer needs.

How SPRINT works
------------------
Unlike other models, it doesn't produce a score in a single forward
pass; instead it's two steps:
  1. `ultrafast-embed --moltype target/drug` encodes proteins and
     molecules into vectors separately
  2. the score is the **cosine similarity** between the two (see
     ultrafast/compute_topk.py)

The protein-side input is a **SaProt structure-aware sequence** (amino
acid and foldseek 3Di tokens alternating), generated by
gen_saprot_seqs.py, which succeeded on all 1,460 targets. Structure
sourcing matches ConGLUDe / the pocket-based models (PDB experimental
structure first, Boltz-2 prediction filling the gaps), keeping the
structural conditioning identical across the comparison.

Unique proteins and unique molecules for the whole layer are encoded
once, then split by target -- molecules repeat heavily across targets,
so encoding per-target would waste tens of times the compute.
"""
import argparse
import json
import os
import subprocess
import sys

import numpy as np

B = "/data/work/vs-benchmark"
SP = f"{B}/code/panspecies-dti"
EMBED = "/data/work/envs/sprint/bin/ultrafast-embed"


def _embed_once(data_file, moltype, out_path, ckpt, gpu, batch=32):
    env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gpu),
               HF_ENDPOINT="https://hf-mirror.com", HF_HOME=f"{B}/hf_cache")
    cmd = [EMBED, "--data-file", data_file, "--moltype", moltype,
           "--checkpoint", ckpt, "--output-path", out_path,
           "--batch-size", str(batch), "--num-workers", "0"]   # 0 workers:
           # each DataLoader worker would open its own copy of the h5/lmdb, and with 146k records that exhausts file handles
    p = subprocess.run(cmd, cwd=SP, env=env, stdout=subprocess.PIPE,
                       stderr=subprocess.STDOUT, text=True)
    if p.returncode != 0 or not os.path.exists(out_path):
        print(p.stdout[-3000:], file=sys.stderr)
        raise SystemExit(f"embed {moltype} 失败 (returncode={p.returncode})")
    return np.load(out_path)


def run_embed(data_file, moltype, out_path, ckpt, gpu, batch=32, chunk=10**9):
    """Embed in batches, then concatenate.

    Handing all 146,000 molecules to ultrafast-embed in one go hangs it --
    observed running for 4 hours without adding a single new record to
    the feature cache, while on the same path L3's 109,000 molecules took
    only 8 minutes. Splitting into smaller batches avoids this (each
    batch is an independent process, so a hang only affects that batch).
    """
    lines = open(data_file).read().rstrip("\n").split("\n")
    header, rows = lines[0], lines[1:]
    if len(rows) <= chunk:
        return _embed_once(data_file, moltype, out_path, ckpt, gpu, batch)

    parts = []
    for i in range(0, len(rows), chunk):
        sub = f"{data_file}.part{i//chunk}"
        with open(sub, "w") as f:
            f.write(header + "\n" + "\n".join(rows[i:i + chunk]) + "\n")
        op = f"{out_path}.part{i//chunk}.npy"
        print(f"    分批 {i//chunk + 1}/{(len(rows)+chunk-1)//chunk}"
              f"（{len(rows[i:i+chunk]):,} 条）", flush=True)
        parts.append(_embed_once(sub, moltype, op, ckpt, gpu, batch))
    out = np.concatenate(parts, axis=0)
    np.save(out_path, out)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--layers", nargs="+", default=["L3", "L4", "L1", "L2"])
    ap.add_argument("--ckpt", default=f"{B}/ckpt/sprint/sprint.ckpt")
    ap.add_argument("--out_dir", default=f"{B}/results/t3_raw/sprint")
    ap.add_argument("--work", default=f"{B}/tmp/sprint_t3")
    ap.add_argument("--gpu", type=int, default=7)
    ap.add_argument("--limit", type=int, default=None,
                    help="每层只取前 N 个靶点。用于在小子集上验证接法是否正确——"
                         "整层 14.6 万分子会让 embed 耗尽文件句柄。")
    args = ap.parse_args()

    seqs = json.load(open(f"{B}/data/t3/saprot_seqs.json"))
    os.makedirs(args.work, exist_ok=True)
    print(f"SaProt 序列库: {len(seqs):,}", flush=True)

    for L in args.layers:
        p = f"{B}/data/t3/eval/{L}.jsonl"
        if not os.path.exists(p):
            print(f"[{L}] 评测集不存在，跳过", flush=True)
            continue
        recs = [json.loads(x) for x in open(p)]
        if args.limit:
            recs = recs[:args.limit]

        usable = [r for r in recs if r["uniprot"] in seqs]
        print(f"[{L}] 靶点 {len(recs)} → 有 SaProt 序列的 {len(usable)}", flush=True)
        if not usable:
            continue

        # Protein side: one row per target
        prots = [r["uniprot"] for r in usable]
        ptsv = f"{args.work}/{L}_target.tsv"
        # Must be written as two tab-separated columns: SPRINT uses
        # pd.read_table(sep=None) to auto-sniff the delimiter, and the
        # header "Target Sequence" contains a space -- with a single
        # column the sniffer treats the space as the delimiter, splitting
        # the column name into Target / Sequence and raising a KeyError.
        # An extra tab-separated column makes it settle on tab.
        with open(ptsv, "w") as f:
            f.write("Target Sequence\tID\n")
            for u in prots:
                f.write(seqs[u]["saprot"] + "\t" + u + "\n")

        # Molecule side: dedup across the whole layer (molecules repeat heavily across targets)
        smi_idx, smiles = {}, []
        per_target = {}
        for r in usable:
            lab = {}
            for kind, y in (("actives", 1), ("decoys", 0)):
                for m in r[kind]:
                    s = m["smiles"]
                    if s not in smi_idx:
                        smi_idx[s] = len(smiles)
                        smiles.append(s)
                    lab[s] = y
            per_target[r["uniprot"]] = lab
        dtsv = f"{args.work}/{L}_drug.tsv"
        with open(dtsv, "w") as f:
            f.write("SMILES\tID\n")
            for i, sm in enumerate(smiles):
                f.write(sm + "\tm%d\n" % i)
        print(f"[{L}] 唯一分子 {len(smiles):,}", flush=True)

        pe = run_embed(ptsv, "target", f"{args.work}/{L}_target.npy", args.ckpt, args.gpu)
        de = run_embed(dtsv, "drug", f"{args.work}/{L}_drug.npy", args.ckpt, args.gpu)
        print(f"[{L}] 蛋白向量 {pe.shape}  分子向量 {de.shape}", flush=True)
        if pe.shape[0] != len(prots) or de.shape[0] != len(smiles):
            raise SystemExit(f"[{L}] 向量数与输入不符，拒绝继续")

        # Cosine similarity: L2-normalize each side first, then take the dot product
        pn = pe / (np.linalg.norm(pe, axis=1, keepdims=True) + 1e-9)
        dn = de / (np.linalg.norm(de, axis=1, keepdims=True) + 1e-9)

        n_ok = 0
        for row, up in enumerate(prots):
            lab = per_target[up]
            cols = [smi_idx[s] for s in lab]
            sc = dn[cols] @ pn[row]
            ys = np.array([lab[s] for s in lab], dtype=np.int8)
            if ys.sum() == 0 or ys.sum() == len(ys):
                continue
            d = f"{args.out_dir}/T3/{L}/{up}"
            os.makedirs(d, exist_ok=True)
            np.save(f"{d}/saved_preds.npy", sc.astype(np.float32))
            np.save(f"{d}/saved_labels.npy", ys)
            n_ok += 1
        print(f"[{L}] 落盘 {n_ok} 个靶点", flush=True)


if __name__ == "__main__":
    main()
